# -*- coding: utf-8 -*-
"""DATASCI final project Yunqi Works final 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2B5zHJwPbwf6pDl-3i0_M4LCzHUxnkx
"""

!pip install geopandas

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

world = gpd.read_file('/content/drive/MyDrive/countries.geo.json')
world

lang = pd.read_csv('/content/drive/MyDrive/Datasci_112_Final_Project/country_annotation.csv')

lang

lang['first_language'] = lang['languages'].str.strip("[]'").str.split("',").str[0]
lang

lang.to_csv("clean_languages.csv", index=False)

# save the csv as a dataframe and sort by publication date
import pandas as pd
output_path = "/content/drive/MyDrive/datasci_hp_cleaned.csv"

path = output_path

df = pd.read_csv(path)
df["published"] = pd.to_datetime(df["published"])
df = df.sort_values("published").reset_index(drop=True)

df

# group languages based on language family
LANGUAGE_FAMILY = {
# English
    "English": "English",
    "Eald Englisċ": "English",  # Old English
# CJK
    "中文-普通话 國語": "CJK",   # Mandarin
    "中文-客家话": "CJK",        # Hakka
    "中文-闽南话 臺語": "CJK",   # Hokkien/Taiwanese
    "中文-吴语": "CJK",          # Wu Chinese
    "中文-广东话 粵語": "CJK",   # Cantonese
    "日本語": "CJK",             # Japanese
    "한국어": "CJK",             # Korean
# Slavic
    "Русский": "Slavic",        # Russian
    "Українська": "Slavic",     # Ukrainian
    "Polski": "Slavic",         # Polish
    "Čeština": "Slavic",        # Czech
    "Slovenčina": "Slavic",     # Slovak
    "Српски": "Slavic",         # Serbian
    "беларуская": "Slavic",     # Belarusian
    "Slovenščina": "Slavic",    # Slovenian
    "Български": "Slavic",      # Bulgarian
  # Romance
    "Español": "Romance",               # Spanish
    "Français": "Romance",              # French
    "Português brasileiro": "Romance",  # Brazilian Portuguese
    "Português europeu": "Romance",     # European Portuguese
    "Italiano": "Romance",              # Italian
    "Română": "Romance",                # Romanian
    "Català": "Romance",                # Catalan

    # Germanic
    "Deutsch": "Germanic",      # German
    "Nederlands": "Germanic",   # Dutch
    "Svenska": "Germanic",      # Swedish
    "Norsk": "Germanic",        # Norwegian
    "Íslenska": "Germanic",     # Icelandic

    # Other Indo-European
    "Latviešu valoda": "Other Indo-European",   # Latvian
    "Lietuvių kalba": "Other Indo-European",    # Lithuanian
    "Ελληνικά": "Other Indo-European",          # Greek
    "հայերեն": "Other Indo-European",           # Armenian

    # Semitic
    "עברית": "Semitic",     # Hebrew
    "العربية": "Semitic",   # Arabic

    # Southeast Asian
    "Tiếng Việt": "Southeast Asian",    # Vietnamese
    "Bahasa Indonesia": "Southeast Asian", # Indonesian
    "ไทย": "Southeast Asian",           # Thai
    "Filipino": "Southeast Asian",      # Filipino

    # Uralic
    "Magyar": "Uralic",     # Hungarian
    "suomi": "Uralic",      # Finnish

    # Turkic
    "Türkçe": "Turkic",     # Turkish

    # Other
    "Esperanto": "Other",
    "Uncategorized Constructed Languages": "Other",
    "አማርኛ": "Other",
}

# map to new column
df["language_family"] = df["language"].map(LANGUAGE_FAMILY)

print(df["language_family"].value_counts())

lang[lang['name']=='Canada']

lang_grouped = pd.read_csv('/content/drive/MyDrive/Datasci_112_Final_Project/clean_languages.csv')
lang_grouped

import pandas as pd

lang_grouped = pd.read_csv('/content/drive/MyDrive/Datasci_112_Final_Project/clean_languages.csv')

STANDARD_FAMILY_DICT = {
    "English": "English",
    "Spanish": "Romance",
    "French": "Romance",
    "Portuguese": "Romance",
    "Italian": "Romance",
    "Romanian": "Romance",
    "Catalan": "Romance",
    "Catalán": "Romance",

    "Russian": "Slavic",
    "Ukrainian": "Slavic",
    "Polish": "Slavic",
    "Czech": "Slavic",
    "Slovak": "Slavic",
    "Serbian": "Slavic",
    "Belarusian": "Slavic",
    "Slovenian": "Slavic",
    "Bulgarian": "Slavic",

    "Chinese": "CJK",
    "Mandarin": "CJK",
    "Japanese": "CJK",
    "Korean": "CJK",

    "German": "Germanic",
    "Dutch": "Germanic",
    "Swedish": "Germanic",
    "Norwegian": "Germanic",
    "Icelandic": "Germanic",
    "Afrikaans": "Germanic",

    "Arabic": "Semitic",
    "Hebrew": "Semitic",

    "Vietnamese": "Southeast Asian",
    "Indonesian": "Southeast Asian",
    "Thai": "Southeast Asian",
    "Filipino": "Southeast Asian",

    "Hungarian": "Uralic",
    "Finnish": "Uralic",

    "Turkish": "Turkic"}
# Map language families
lang_grouped["language_family"] = lang_grouped["first_language"].map(STANDARD_FAMILY_DICT)

# Remove countries that could not be mapped to a language family
matched_family_df = lang_grouped.dropna(subset=["language_family"]).copy()

# Create the final table
result_family_df = matched_family_df[["name","language_family"]].reset_index(drop=True)

# Rename column (if you want it to be called "Country")
result_family_df = result_family_df.rename(columns={"name":"Country"})
result_family_df

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

# =========================
# 1. Load language data
# =========================
lang_grouped = pd.read_csv('/content/drive/MyDrive/Datasci_112_Final_Project/clean_languages.csv')

# If "first_language" does not exist, this will raise an error.
# Your dataset already contains it, so it's fine.
# Expected columns: code, name, continent, languages, first_language

# =========================
# 2. Map language families
# =========================
STANDARD_FAMILY_DICT = {
    "English": "English",

    "Spanish": "Romance",
    "French": "Romance",
    "Portuguese": "Romance",
    "Italian": "Romance",
    "Romanian": "Romance",
    "Catalan": "Romance",
    "Catalán": "Romance",

    "Russian": "Slavic",
    "Ukrainian": "Slavic",
    "Polish": "Slavic",
    "Czech": "Slavic",
    "Slovak": "Slavic",
    "Serbian": "Slavic",
    "Belarusian": "Slavic",
    "Slovenian": "Slavic",
    "Bulgarian": "Slavic",

    "Chinese": "CJK",
    "Mandarin": "CJK",
    "Japanese": "CJK",
    "Korean": "CJK",

    "German": "Germanic",
    "Dutch": "Germanic",
    "Swedish": "Germanic",
    "Norwegian": "Germanic",
    "Icelandic": "Germanic",
    "Afrikaans": "Germanic",

    "Arabic": "Semitic",
    "Hebrew": "Semitic",
    "Hassaniya Arabic": "Semitic",

    "Vietnamese": "Southeast Asian",
    "Indonesian": "Southeast Asian",
    "Thai": "Southeast Asian",
    "Filipino": "Southeast Asian",

    "Hungarian": "Uralic",
    "Finnish": "Uralic",

    "Turkish": "Turkic",

    "Greek": "Other Indo-European",
    "Armenian": "Other Indo-European",
    "Latvian": "Other Indo-European",
    "Lithuanian": "Other Indo-European",
    "Albanian": "Other Indo-European",
    "Persian": "Other Indo-European",
    "Dari Persian": "Other Indo-European",

    "Amharic": "Other",
    "Esperanto": "Other"
}

lang_grouped["language_family"] = lang_grouped["first_language"].map(STANDARD_FAMILY_DICT)

# =========================
# 3. Add work counts (from your screenshot)
#    Countries in the same family share the same count
# =========================
FAMILY_COUNT = {
    "English": 100066,
    "Romance": 5938,
    "Slavic": 4737,
    "CJK": 3743,
    "Germanic": 658,
    "Turkic": 327,
    "Southeast Asian": 221,
    "Uralic": 178,
    "Other Indo-European": 15,
    "Semitic": 10,
    "Other": 5
}

lang_grouped["count"] = lang_grouped["language_family"].map(FAMILY_COUNT)

# Keep only countries with a mapped language family
map_df = lang_grouped.dropna(subset=["language_family"]).copy()

# =========================
# 4. Standardize country names for merging
# =========================
country_fix = {
    "United States": "United States of America",
    "Dominican Republic": "Dominican Rep.",
    "Czech Republic": "Czechia",
    "Bosnia and Herzegovina": "Bosnia and Herz.",
    "Myanmar (Burma)": "Myanmar",
    "Eswatini": "eSwatini",
    "North Macedonia": "Macedonia",
    "Western Sahara (proposed state)": "W. Sahara",
    "Democratic Republic of the Congo": "Dem. Rep. Congo",
    "Republic of the Congo": "Congo",
    "South Sudan": "S. Sudan",
    "Central African Republic": "Central African Rep.",
    "Equatorial Guinea": "Eq. Guinea",
    "Solomon Islands": "Solomon Is.",
    "Timor-Leste": "East Timor"
}

map_df["country_map"] = map_df["name"].replace(country_fix)

# =========================
# 5. Load world map
# =========================
world = gpd.read_file(
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"
)

# Remove Antarctica for cleaner visualization
world = world[world["NAME"] != "Antarctica"].copy()

# Merge data with map
merged = world.merge(
    map_df[["country_map", "language_family", "count"]],
    how="left",
    left_on="NAME",
    right_on="country_map"
)

# =========================
# 6. Color scheme:
#    Hue = language family
#    Lightness = work count
# =========================
base_colors = {
    "English": "#4C78A8",
    "Romance": "#E45756",
    "Slavic": "#7A5195",
    "CJK": "#54A24B",
    "Germanic": "#F58518",
    "Turkic": "#72B7B2",
    "Southeast Asian": "#DA70D6",
    "Uralic": "#8C8C8C",
    "Other Indo-European": "#17BECF",
    "Semitic": "#B279A2",
    "Other": "#BAB0AC"
}

# Log scaling to reduce dominance of large values (e.g., 100066)
merged["log_count"] = np.log1p(merged["count"])

# Default color (no data)
merged["plot_color"] = "#D9D9D9"

# Compute total works
total_works = merged["count"].sum()

# Compute share
merged["share"] = merged["count"] / total_works

# Generate colors
for family, hex_color in base_colors.items():

    mask = merged["language_family"] == family
    if mask.sum() == 0:
        continue

    vals = merged.loc[mask, "share"]
    vmin, vmax = vals.min(), vals.max()

    if vmin == vmax:
        norm_vals = [0.6] * len(vals)
    else:
        norm_vals = (vals - vmin) / (vmax - vmin)

    rgb = np.array(mcolors.to_rgb(hex_color))
    white = np.array([1,1,1])

    colors = []
    for a in norm_vals:
        # Higher values → closer to base color; lower values → closer to white
        mixed = white * (1 - a) + rgb * a
        colors.append(mcolors.to_hex(mixed))

    merged.loc[mask, "plot_color"] = colors

# =========================
# 7. Plot map
# =========================
fig, ax = plt.subplots(figsize=(18, 10))

merged.plot(
    color=merged["plot_color"],
    edgecolor="black",
    linewidth=0.25,
    ax=ax
)

ax.set_title(
    "World Map of Primary Language Families\nHue = Language Family, Lightness = Work Count",
    fontsize=16
)
ax.axis("off")

# =========================
# 8. Manual legend
# =========================
from matplotlib.patches import Patch

legend_handles = [
    Patch(facecolor=base_colors[fam], edgecolor="black", label=fam)
    for fam in base_colors.keys()
]

legend_handles.append(
    Patch(facecolor="#D9D9D9", edgecolor="black", label="No data")
)

ax.legend(
    handles=legend_handles,
    title="Language Family",
    loc="lower left",
    bbox_to_anchor=(0.02, 0.02),
    frameon=True,
    fontsize=10,
    title_fontsize=11
)

plt.tight_layout()
plt.show()

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
from matplotlib.patches import Patch

# =========================
# 1. Load language data
# =========================
lang_grouped = pd.read_csv('/content/drive/MyDrive/Datasci_112_Final_Project/clean_languages.csv')

# =========================
# 2. Map language families
# =========================
STANDARD_FAMILY_DICT = {
    "English": "English",

    "Spanish": "Romance",
    "French": "Romance",
    "Portuguese": "Romance",
    "Italian": "Romance",
    "Romanian": "Romance",
    "Catalan": "Romance",
    "Catalán": "Romance",

    "Russian": "Slavic",
    "Ukrainian": "Slavic",
    "Polish": "Slavic",
    "Czech": "Slavic",
    "Slovak": "Slavic",
    "Serbian": "Slavic",
    "Belarusian": "Slavic",
    "Slovenian": "Slavic",
    "Bulgarian": "Slavic",

    "Chinese": "CJK",
    "Mandarin": "CJK",
    "Japanese": "CJK",
    "Korean": "CJK",

    "German": "Germanic",
    "Dutch": "Germanic",
    "Swedish": "Germanic",
    "Norwegian": "Germanic",
    "Icelandic": "Germanic",
    "Afrikaans": "Germanic",

    "Arabic": "Semitic",
    "Hebrew": "Semitic",
    "Hassaniya Arabic": "Semitic",

    "Vietnamese": "Southeast Asian",
    "Indonesian": "Southeast Asian",
    "Thai": "Southeast Asian",
    "Filipino": "Southeast Asian",

    "Hungarian": "Uralic",
    "Finnish": "Uralic",

    "Turkish": "Turkic",

    "Greek": "Other Indo-European",
    "Armenian": "Other Indo-European",
    "Latvian": "Other Indo-European",
    "Lithuanian": "Other Indo-European",
    "Albanian": "Other Indo-European",
    "Persian": "Other Indo-European",
    "Dari Persian": "Other Indo-European",

    "Amharic": "Other",
    "Esperanto": "Other"
}

lang_grouped["language_family"] = lang_grouped["first_language"].map(STANDARD_FAMILY_DICT)

# =========================
# 3. Family-level work counts
# =========================
FAMILY_COUNT = {
    "English": 100066,
    "Romance": 5938,
    "Slavic": 4737,
    "CJK": 3743,
    "Germanic": 658,
    "Turkic": 327,
    "Southeast Asian": 221,
    "Uralic": 178,
    "Other Indo-European": 15,
    "Semitic": 10,
    "Other": 5
}

lang_grouped["count"] = lang_grouped["language_family"].map(FAMILY_COUNT)

# =========================
# 4. Compute share of total works
# =========================
total_works = sum(FAMILY_COUNT.values())
lang_grouped["share"] = lang_grouped["count"] / total_works

# Keep only countries with a mapped language family
map_df = lang_grouped.dropna(subset=["language_family"]).copy()

# =========================
# 5. Standardize country names
# =========================
country_fix = {
    "United States": "United States of America",
    "Dominican Republic": "Dominican Rep.",
    "Czech Republic": "Czechia",
    "Bosnia and Herzegovina": "Bosnia and Herz.",
    "Myanmar (Burma)": "Myanmar",
    "Eswatini": "eSwatini",
    "North Macedonia": "Macedonia",
    "Western Sahara (proposed state)": "W. Sahara",
    "Democratic Republic of the Congo": "Dem. Rep. Congo",
    "Republic of the Congo": "Congo",
    "South Sudan": "S. Sudan",
    "Central African Republic": "Central African Rep.",
    "Equatorial Guinea": "Eq. Guinea",
    "Solomon Islands": "Solomon Is.",
    "Timor-Leste": "East Timor"
}

map_df["country_map"] = map_df["name"].replace(country_fix)

# =========================
# 6. Load world map
# =========================
world = gpd.read_file(
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"
)
world = world[world["NAME"] != "Antarctica"].copy()

merged = world.merge(
    map_df[["country_map", "language_family", "count", "share"]],
    how="left",
    left_on="NAME",
    right_on="country_map"
)

# =========================
# 7. Color design:
#    Hue = language family
#    Lightness = share
# =========================
base_colors = {
    "English": "#4C78A8",
    "Romance": "#E45756",
    "Slavic": "#7A5195",
    "CJK": "#54A24B",
    "Germanic": "#F58518",
    "Turkic": "#72B7B2",
    "Southeast Asian": "#DA70D6",
    "Uralic": "#8C8C8C",
    "Other Indo-European": "#17BECF",
    "Semitic": "#B279A2",
    "Other": "#BAB0AC"
}

# Default color for missing data
merged["plot_color"] = "#D9D9D9"

# English dominates heavily → linear mapping would flatten others
# Use log transformation for better contrast
family_share = pd.Series(FAMILY_COUNT) / total_works
family_share_log = np.log1p(family_share)
family_share = np.sqrt(family_share)

log_min = family_share_log.min()
log_max = family_share_log.max()

for family, hex_color in base_colors.items():
    mask = merged["language_family"] == family
    if mask.sum() == 0:
        continue

    s = family_share[family]
    s_log = np.log1p(s)

    # Normalize globally (not within each family)
    if log_max == log_min:
        a = 0.7
    else:
        a = 0.25 + 0.75 * (s_log - log_min) / (log_max - log_min)

    rgb = np.array(mcolors.to_rgb(hex_color))
    white = np.array([1, 1, 1])

    mixed = white * (1 - a) + rgb * a
    color_hex = mcolors.to_hex(mixed)

    merged.loc[mask, "plot_color"] = color_hex

# =========================
# 8. Plot map
# =========================
fig, ax = plt.subplots(figsize=(18, 10))

merged.plot(
    color=merged["plot_color"],
    edgecolor="black",
    linewidth=0.25,
    ax=ax
)

ax.set_title(
    "World Map of Primary Language Families\nColor hue = family, color depth = share of total works",
    fontsize=16
)
ax.axis("off")

# =========================
# 9. Legend
# =========================
legend_handles = []
for fam in base_colors.keys():
    pct = family_share[fam] * 100
    legend_handles.append(
        Patch(
            facecolor=merged.loc[merged["language_family"] == fam, "plot_color"].iloc[0]
            if (merged["language_family"] == fam).any() else base_colors[fam],
            edgecolor="black",
            label=f"{fam} ({pct:.2f}%)"
        )
    )

legend_handles.append(
    Patch(facecolor="#D9D9D9", edgecolor="black", label="No data")
)

ax.legend(
    handles=legend_handles,
    title="Language Family Share",
    loc="lower left",
    bbox_to_anchor=(0.02, 0.02),
    frameon=True,
    fontsize=10,
    title_fontsize=11
)

plt.tight_layout()
plt.show()

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.colors import PowerNorm

# =========================
# 1. Load world map
# =========================
world = gpd.read_file(
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"
)

# =========================
# 2. Load pre-2010 dataset
# =========================
before_df = pd.read_csv("before_2010.csv")
before_df.columns = ["country", "value"]

# =========================
# 3. Align country names
# =========================
country_name_map = {
    "United States": "United States of America",
    "United Kingdom": "United Kingdom",
    "Czech Republic": "Czechia",
    "Russia": "Russia",
    "Taiwan": "Taiwan",
    "Korea": "South Korea",
    "South Korea": "South Korea",
    "North Macedonia": "Macedonia",
    "Bosnia and Herzegovina": "Bosnia and Herz.",
}

before_df["country"] = before_df["country"].replace(country_name_map)

before_df = before_df[~before_df["country"].isin([
    "Continent-wide events",
    "Europe-wide events",
    "Asia-wide events",
    "Africa-wide events"
])]

# =========================
# 4. Compute share
# =========================
before_df["share"] = before_df["value"] / before_df["value"].sum()

# =========================
# 5. Merge with world map
# =========================
world_before = world.merge(
    before_df,
    how="left",
    left_on="NAME",
    right_on="country"
)

# Remove Antarctica for a cleaner map
world_before = world_before[world_before["NAME"] != "Antarctica"].copy()

# =========================
# 6. PowerNorm (enhance visibility of low values)
# =========================
share_norm = PowerNorm(
    gamma=1,
    vmin=0,
    vmax=before_df["share"].max()
)

# =========================
# 7. Plot map
# =========================
fig, ax = plt.subplots(figsize=(14,7))

# Choropleth map
world_before.plot(
    column="share",
    cmap="Purples",
    linewidth=0.3,
    edgecolor="white",
    missing_kwds={
        "color": "#e6e6e6",
        "edgecolor": "white",
        "label": "No data"
    },
    norm=share_norm,
    legend=True,
    ax=ax
)

# Overlay country boundaries for clarity
world.boundary.plot(
    ax=ax,
    linewidth=0.6,
    color="black"
)

ax.set_title("Share of Global LGBTQ Parades (1986–2009)", fontsize=16, pad=15)
ax.axis("off")

plt.tight_layout()
plt.show()

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# =========================
# 1. Load world map
# =========================
world = gpd.read_file(
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"
)

# =========================
# 2. Load the three datasets
#    Adjust file paths if needed
# =========================
before_df = pd.read_csv("before_2010.csv")
after_df  = pd.read_csv("from_2010.csv")
all_df    = pd.read_csv("all_time.csv")

# Ensure consistent column names
before_df.columns = ["country", "value"]
after_df.columns  = ["country", "value"]
all_df.columns    = ["country", "value"]

# =========================
# 3. Clean and align country names with shapefile
# =========================
country_name_map = {
    "United States": "United States of America",
    "United Kingdom": "United Kingdom",
    "Czech Republic": "Czechia",
    "Taiwan": "Taiwan",
    "Russia": "Russia",
    "South Korea": "South Korea",
    "Korea": "South Korea",   # If "Korea" refers to South Korea; remove if uncertain
    "North Macedonia": "Macedonia",
    "Bosnia and Herzegovina": "Bosnia and Herz.",
}

def clean_country_names(df):
    df = df.copy()
    df["country"] = df["country"].replace(country_name_map)

    # Remove entries that do not correspond to a single country
    df = df[~df["country"].isin([
        "Continent-wide events",
        "Europe-wide events",
        "Asia-wide events",
        "Africa-wide events"
    ])]

    return df

before_df = clean_country_names(before_df)
after_df  = clean_country_names(after_df)
all_df    = clean_country_names(all_df)

# =========================
# 4. Compute share
# =========================
before_df["share"] = before_df["value"] / before_df["value"].sum()
after_df["share"]  = after_df["value"] / after_df["value"].sum()
all_df["share"]    = all_df["value"] / all_df["value"].sum()

# =========================
# 5. Merge with world map
# =========================
world_before = world.merge(before_df, how="left", left_on="NAME", right_on="country")
world_after  = world.merge(after_df,  how="left", left_on="NAME", right_on="country")
world_all    = world.merge(all_df,    how="left", left_on="NAME", right_on="country")

# =========================
# 6. Use a shared color scale for comparability
# =========================
global_value_max = max(
    before_df["value"].max(),
    after_df["value"].max(),
    all_df["value"].max()
)

# Same logic for share
global_share_max = max(
    before_df["share"].max(),
    after_df["share"].max(),
    all_df["share"].max()
)

value_norm = mcolors.Normalize(vmin=0, vmax=global_value_max)
share_norm = mcolors.Normalize(vmin=0, vmax=global_share_max)

# =========================
# 7. Plotting function
# =========================
def plot_map(gdf, column, ax, title, norm):
    gdf.plot(
        column=column,
        ax=ax,
        cmap="Blues",
        linewidth=0.4,
        edgecolor="black",
        missing_kwds={
            "color": "lightgrey",
            "edgecolor": "white",
            "label": "No data"
        },
        norm=norm,
        legend=True
    )
    ax.set_title(title, fontsize=12)
    ax.axis("off")

# =========================
# 8. Create 2×3 panel of maps
# =========================
fig, axes = plt.subplots(2, 3, figsize=(22, 10))

# Row 1: raw counts
plot_map(world_before, "value", axes[0, 0], "Before 2010 — Raw Count", value_norm)
plot_map(world_after,  "value", axes[0, 1], "From 2010 — Raw Count", value_norm)
plot_map(world_all,    "value", axes[0, 2], "All Time — Raw Count", value_norm)

# Row 2: shares
plot_map(world_before, "share", axes[1, 0], "Before 2010 — Share of Global Total", share_norm)
plot_map(world_after,  "share", axes[1, 1], "From 2010 — Share of Global Total", share_norm)
plot_map(world_all,    "share", axes[1, 2], "All Time — Share of Global Total", share_norm)

plt.tight_layout()
plt.show()

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.colors import PowerNorm

# =========================
# 0. File paths
# =========================
WORLD_PATH = "/content/drive/MyDrive/countries.geo.json"
LANG_PATH = "/content/drive/MyDrive/Datasci_112_Final_Project/clean_languages.csv"
FAMILY_PATH = "/content/drive/MyDrive/Datasci_112_Final_Project/lgbtq_by_family.csv"

# =========================
# 1. Load files
# =========================
world = gpd.read_file(WORLD_PATH)
lang = pd.read_csv(LANG_PATH)
family = pd.read_csv(FAMILY_PATH)

# Check column names in case of extra spaces
world.columns = world.columns.str.strip()
lang.columns = lang.columns.str.strip()
family.columns = family.columns.str.strip()

print("world columns:", world.columns.tolist())
print("lang columns:", lang.columns.tolist())
print("family columns:", family.columns.tolist())

# =========================
# 2. Make sure the family table has the correct column names
#    Target columns: language_family, prop_lgbtq
# =========================
family = family.rename(columns={
    "Language Family": "language_family",
    "prop_lgbtq ": "prop_lgbtq"
})

family["language_family"] = family["language_family"].astype(str).str.strip()
family["prop_lgbtq"] = pd.to_numeric(family["prop_lgbtq"], errors="coerce")

family = family[["language_family", "prop_lgbtq"]].dropna()

# =========================
# 3. Map first_language to language_family
# =========================
STANDARD_FAMILY_DICT = {
    "English": "English",

    "Spanish": "Romance",
    "French": "Romance",
    "Portuguese": "Romance",
    "Italian": "Romance",
    "Romanian": "Romance",
    "Catalan": "Romance",
    "Catalán": "Romance",

    "Russian": "Slavic",
    "Ukrainian": "Slavic",
    "Polish": "Slavic",
    "Czech": "Slavic",
    "Slovak": "Slavic",
    "Serbian": "Slavic",
    "Belarusian": "Slavic",
    "Slovenian": "Slavic",
    "Bulgarian": "Slavic",

    "Chinese": "CJK",
    "Mandarin": "CJK",
    "Japanese": "CJK",
    "Korean": "CJK",

    "German": "Germanic",
    "Dutch": "Germanic",
    "Swedish": "Germanic",
    "Norwegian": "Germanic",
    "Icelandic": "Germanic",
    "Afrikaans": "Germanic",

    "Arabic": "Semitic",
    "Hebrew": "Semitic",
    "Hassaniya Arabic": "Semitic",

    "Vietnamese": "Southeast Asian",
    "Indonesian": "Southeast Asian",
    "Thai": "Southeast Asian",
    "Filipino": "Southeast Asian",

    "Hungarian": "Uralic",
    "Finnish": "Uralic",

    "Turkish": "Turkic",

    "Greek": "Other Indo-European",
    "Armenian": "Other Indo-European",
    "Latvian": "Other Indo-European",
    "Lithuanian": "Other Indo-European",
    "Albanian": "Other Indo-European",
    "Persian": "Other Indo-European",
    "Dari Persian": "Other Indo-European",

    "Amharic": "Other",
    "Esperanto": "Other"
}

lang["first_language"] = lang["first_language"].astype(str).str.strip()
lang["language_family"] = lang["first_language"].map(STANDARD_FAMILY_DICT)

# Keep only countries that can be mapped to a language family
lang_map = lang.dropna(subset=["language_family"]).copy()

# =========================
# 4. Merge in family-level proportions
# =========================
lang_map["language_family"] = lang_map["language_family"].astype(str).str.strip()

lang_map = lang_map.merge(
    family,
    on="language_family",
    how="left"
)

# =========================
# 5. Align country names
#    In your world file, the column is "name", not "NAME"
# =========================
country_fix = {
    "United States": "United States of America",
    "Dominican Republic": "Dominican Rep.",
    "Czech Republic": "Czechia",
    "Bosnia and Herzegovina": "Bosnia and Herz.",
    "Myanmar (Burma)": "Myanmar",
    "Eswatini": "eSwatini",
    "North Macedonia": "Macedonia",
    "Western Sahara (proposed state)": "W. Sahara",
    "Democratic Republic of the Congo": "Dem. Rep. Congo",
    "Republic of the Congo": "Congo",
    "South Sudan": "S. Sudan",
    "Central African Republic": "Central African Rep.",
    "Equatorial Guinea": "Eq. Guinea",
    "Solomon Islands": "Solomon Is.",
    "Timor-Leste": "East Timor",
    "Cape Verde": "Cabo Verde"
}

lang_map["country_map"] = lang_map["name"].replace(country_fix)

# Remove duplicates to avoid repeated countries
lang_map = lang_map[["country_map", "language_family", "prop_lgbtq"]].drop_duplicates()

# =========================
# 6. Merge with map
# =========================
merged = world.merge(
    lang_map,
    how="left",
    left_on="name",
    right_on="country_map"
)

# Optional: remove Antarctica
merged = merged[merged["name"] != "Antarctica"].copy()

print("Matched countries:", merged["prop_lgbtq"].notna().sum())

# =========================
# 7. Plot
# =========================
fig, ax = plt.subplots(figsize=(18, 10))

norm = PowerNorm(
    gamma=1,   # Makes low values more visible; use 0.35 for a stronger effect
    vmin=0,
    vmax=merged["prop_lgbtq"].max()
)

merged.plot(
    column="prop_lgbtq",
    cmap="Reds",
    linewidth=0.4,
    edgecolor="white",
    norm=norm,
    legend=True,
    missing_kwds={
        "color": "#e6e6e6",
        "edgecolor": "white",
        "label": "No data"
    },
    ax=ax
)

# Add boundaries
merged.boundary.plot(
    ax=ax,
    linewidth=0.35,
    color="black"
)

ax.set_title(
    "Share of LGBTQ Works on AO3 by Language Family (2009-2025)",
    fontsize=16,
    pad=14
)
ax.axis("off")

plt.tight_layout()
plt.show()