# -*- coding: utf-8 -*-
"""DATASCI final project Yunqi Works final 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nEJEdqr4O2TiNlcIwA3j_fCHrD_mTfB5
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import re

url = "https://en.wikipedia.org/wiki/List_of_LGBTQ_events"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

# Find all wikitable tables
tables = soup.find_all("table", class_="wikitable")

all_rows = []

for table_idx, table in enumerate(tables):
    # 1. Find continent (nearest h2)
    continent_tag = table.find_previous("h2")
    if continent_tag:
        continent = continent_tag.get_text(" ", strip=True).replace("[edit]", "").strip()
    else:
        continent = None

    # 2. Find table header
    first_tr = table.find("tr")
    if first_tr is None:
        continue

    ths = first_tr.find_all("th")
    colnames = [th.get_text(" ", strip=True).replace("[edit]", "").strip() for th in ths]

    # Only keep the first 5 columns
    if len(colnames) >= 5:
        colnames = colnames[:5]
    else:
        colnames = ["LGBT event", "Location", "Official website", "Occurs every", "Start"]

    current_country = None

    # 3. Iterate through each row
    for tr in table.find_all("tr")[1:]:
        tds = tr.find_all("td")

        if len(tds) == 0:
            continue

        # 4. Country grouping row: only one td with colspan
        if len(tds) == 1 and tds[0].has_attr("colspan"):
            h3 = tds[0].find("h3")
            if h3:
                current_country = h3.get_text(" ", strip=True)
            else:
                current_country = tds[0].get_text(" ", strip=True)

            current_country = current_country.replace("[edit]", "").strip()
            continue

        # 5. Regular event row: strictly keep first 5 cells, preserve empty values
        row = []
        for i in range(5):
            if i < len(tds):
                text = tds[i].get_text(" ", strip=True)
                text = re.sub(r"\[\d+\]", "", text).strip()
                row.append(text if text != "" else None)
            else:
                row.append(None)

        record = dict(zip(colnames, row))
        record["continent"] = continent
        record["country"] = current_country
        record["table_index"] = table_idx

        all_rows.append(record)

# Convert to DataFrame
df = pd.DataFrame(all_rows)

# Reorder columns
preferred_order = [
    "continent",
    "country",
    "LGBT event",
    "Location",
    "Official website",
    "Occurs every",
    "Start",
    "table_index"
]

df = df[[c for c in preferred_order if c in df.columns] + [c for c in df.columns if c not in preferred_order]]

# Convert pure whitespace strings to missing values
df = df.replace(r"^\s*$", pd.NA, regex=True).dropna(subset=["Start"])

df

df[df["Occurs every"].isna()]

import pandas as pd
import numpy as np


df = df.dropna(subset=["Start"]).copy()
df["Start"] = pd.to_numeric(df["Start"], errors="coerce")
df = df.dropna(subset=["Start"]).copy()
df["Start"] = df["Start"].astype(int)


df["is_recurring"] = df["Occurs every"].notna()


end_year = 2026

all_event_years = []

for _, row in df.iterrows():
    start = row["Start"]

    if row["is_recurring"]:
        years = range(start, end_year + 1)
    else:
        years = [start]

    for y in years:
        all_event_years.append(y)

year_counts = pd.Series(all_event_years).value_counts().sort_index()
year_counts.name = "num_events"

year_counts

year_counts_df = year_counts.reset_index()
year_counts_df.columns = ["year", "num_events"]

year_counts_df.to_csv("year_event_counts.csv", index=False)

import pandas as pd

df = df.copy()

# 清洗 Occurs every 空字符串
df["Occurs every"] = df["Occurs every"].replace(r"^\s*$", pd.NA, regex=True)

# 清洗 Start
df = df.dropna(subset=["Start"]).copy()
df["Start"] = pd.to_numeric(df["Start"], errors="coerce")
df = df.dropna(subset=["Start"])
df["Start"] = df["Start"].astype(int)

end_year = 2026

rows = []

for _, r in df.iterrows():
    start = r["Start"]
    country = r["country"]

    # recurring event
    if pd.notna(r["Occurs every"]):
        years = range(start, end_year + 1)
    else:
        years = [start]

    for y in years:
        rows.append({
            "year": y,
            "country": country
        })

year_country_df = pd.DataFrame(rows)

year_country_counts = (
    year_country_df
    .groupby(["year", "country"])
    .size()
    .reset_index(name="num_events")
)

year_country_counts

events_summary = pd.DataFrame({
    "before_2010": year_country_counts[year_country_counts["year"] < 2010]
        .groupby("country")["num_events"].sum(),
    "from_2010": year_country_counts[year_country_counts["year"] >= 2010]
        .groupby("country")["num_events"].sum(),
    "all_time": year_country_counts
        .groupby("country")["num_events"].sum(),
}).fillna(0).astype(int)

events_summary = events_summary.sort_values("all_time", ascending=False)

events_summary_reset = events_summary.reset_index()
# 1. before 2010 dataset
before_2010_df = events_summary_reset[["country", "before_2010"]]
# 2. from 2010 dataset
from_2010_df = events_summary_reset[["country", "from_2010"]]

# 3. all time dataset
all_time_df = events_summary_reset[["country", "all_time"]]


before_2010_df.to_csv("before_2010.csv", index=False)
from_2010_df.to_csv("from_2010.csv", index=False)
all_time_df.to_csv("all_time.csv", index=False)